# Generated by Django 4.1.7 on 2023-03-07 11:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('tax_id', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('untaxed_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('taxed_total', models.DecimalField(decimal_places=0, max_digits=10)),
                ('payment_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('payment_received_date', models.DateField(blank=True, null=True)),
                ('bank_account', models.CharField(max_length=10)),
                ('invoice_number', models.CharField(max_length=20)),
                ('order_date', models.DateField()),
                ('note', models.CharField(max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting_tracker.company')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting_tracker.payment_type')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting_tracker.contact'),
        ),
    ]
