# Generated by Django 4.1.7 on 2023-03-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tracker', '0003_alter_contact_email_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact',
        ),
        migrations.AddField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='contacts', to='accounting_tracker.contact'),
        ),
    ]
