# Generated by Django 4.1.7 on 2023-03-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tracker', '0004_remove_company_contact_company_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(related_name='contacts', to='accounting_tracker.contact'),
        ),
    ]
