# Generated by Django 4.1.7 on 2023-03-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tracker', '0006_rename_payment_type_paymenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='contacts', to='accounting_tracker.contact'),
        ),
    ]
