# Generated by Django 4.1.7 on 2023-03-16 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tracker', '0010_order_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
