# Generated by Django 4.1.7 on 2023-03-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tracker', '0012_rename_notes_company_note_rename_notes_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
